version: '3.8'

services:
  database:
    image: postgres:16
    container_name: database-container
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: steam-db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - steam-nuage-data:/var/lib/postgres/data

  steam-nuage:
    container_name: steam-nuage
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DIALECT: ${DB_DIALECT}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
    ports:
      - "5050:8080"
    depends_on:
      database:
        condition: service_started

volumes:
  steam-nuage-data: