version: '3.8'

services:
  database:
    image: postgres:16
    container_name: database-container
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: steam-db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - steam_nuage_data_dev:/var/lib/postgres/data

  pgadmin:
    container_name: database-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  steam_nuage_data_dev: